/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import static View.GUI_Index.panelChamar;
import javax.swing.JOptionPane;

/**
 *
 * @author lab0519
 */
public class GUI_GerarPerguntas extends javax.swing.JFrame {

static String [] perguntas = new String[1000];
static int cont=1;
static boolean voltar=false;
    public GUI_GerarPerguntas() {
        initComponents();
        
        txtqtd.setValue(1);
      for(int i=0; i < 1000; i++){
      perguntas[i] = "";
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpergunta = new javax.swing.JTextArea();
        lblD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        lblnum = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblqtd = new javax.swing.JLabel();
        txtqtd = new javax.swing.JSpinner();
        txtE = new javax.swing.JTextField();
        lblE = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMaximumSize(new java.awt.Dimension(545, 395));
        panel.setMinimumSize(new java.awt.Dimension(545, 395));
        panel.setPreferredSize(new java.awt.Dimension(545, 395));
        panel.setLayout(null);

        txtpergunta.setColumns(20);
        txtpergunta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtpergunta.setLineWrap(true);
        txtpergunta.setRows(5);
        txtpergunta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtpergunta);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 470, 91);

        lblD.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD.setText("D)");
        lblD.setEnabled(false);
        panel.add(lblD);
        lblD.setBounds(30, 290, 30, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1416623552_flag_finish.png"))); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(280, 350, 100, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus.png"))); // NOI18N
        jButton2.setText("Nova Pergunta");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(410, 40, 120, 20);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PERGUNTAS");
        panel.add(jLabel10);
        jLabel10.setBounds(0, 10, 550, 30);

        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        op1.setText("A,B,C,D,E");
        op1.setContentAreaFilled(false);
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        panel.add(op1);
        op1.setBounds(170, 170, 80, 20);

        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        op2.setText("Linhas");
        op2.setContentAreaFilled(false);
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });
        panel.add(op2);
        op2.setBounds(340, 170, 70, 20);

        lblnum.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnum.setText("1.");
        panel.add(lblnum);
        lblnum.setBounds(20, 70, 30, 30);

        lblA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblA.setText("A)");
        lblA.setEnabled(false);
        panel.add(lblA);
        lblA.setBounds(30, 200, 30, 20);

        lblB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB.setText("B)");
        lblB.setEnabled(false);
        panel.add(lblB);
        lblB.setBounds(30, 230, 30, 20);

        lblC.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC.setText("C)");
        lblC.setEnabled(false);
        panel.add(lblC);
        lblC.setBounds(30, 260, 30, 20);

        txtD.setEnabled(false);
        panel.add(txtD);
        txtD.setBounds(60, 290, 470, 20);

        txtA.setEnabled(false);
        panel.add(txtA);
        txtA.setBounds(60, 200, 470, 20);

        txtB.setEnabled(false);
        panel.add(txtB);
        txtB.setBounds(60, 230, 470, 20);

        txtC.setEnabled(false);
        panel.add(txtC);
        txtC.setBounds(60, 260, 470, 20);

        lblqtd.setText("Quantidade:");
        lblqtd.setEnabled(false);
        panel.add(lblqtd);
        lblqtd.setBounds(430, 170, 70, 20);

        txtqtd.setEnabled(false);
        txtqtd.setFocusable(false);
        txtqtd.setName(""); // NOI18N
        panel.add(txtqtd);
        txtqtd.setBounds(500, 170, 29, 20);

        txtE.setEnabled(false);
        panel.add(txtE);
        txtE.setBounds(60, 320, 470, 20);

        lblE.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblE.setText("E)");
        lblE.setEnabled(false);
        panel.add(lblE);
        lblE.setBounds(30, 320, 30, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/GoBack.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel.add(jButton4);
        jButton4.setBounds(10, 350, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1416623523_edit-clear.png"))); // NOI18N
        jButton3.setText("Limpar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel.add(jButton3);
        jButton3.setBounds(180, 350, 90, 30);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 545, 395);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(txtpergunta.getText().equals("")){

}else{    
      perguntas[cont] = perguntas[cont] + cont +"-"+txtpergunta.getText() + "\n";
        
         if (op1.isSelected()){
      
               perguntas[cont] = perguntas[cont] + "A) " + txtA.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "B) " + txtB.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "C) " + txtC.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "D) " + txtD.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "E) " + txtE.getText() + "\n";
               
           
                          }else{        
            if (op2.isSelected()){
              int linhas = Integer.parseInt(txtqtd.getValue().toString());
              for(int i=1; i <= linhas ; i++){
                   perguntas[cont]= perguntas[cont]+ "__________________________________________________________";
                 perguntas[cont]= perguntas[cont]+ "_____________________________" + "\n";
              }
               
                 
         }else{
                      
           JOptionPane.showMessageDialog(null,"Selecione a opção de respostas");           
                      }
         
         }
}
          
           panelChamar.setViewportView(new GUI_Finalizar().panel); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
       txtqtd.setEnabled(true);
       lblqtd.setEnabled(true);
       
        txtA.setEnabled(false);
    txtB.setEnabled(false);
    txtC.setEnabled(false);
    txtD.setEnabled(false);  
     txtE.setEnabled(false);
      lblA.setEnabled(false);
    lblB.setEnabled(false);
    lblC.setEnabled(false);
    lblD.setEnabled(false);
     lblE.setEnabled(false);
    }//GEN-LAST:event_op2ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
    txtA.setEnabled(true);
    txtB.setEnabled(true);
    txtC.setEnabled(true);
    txtD.setEnabled(true); 
    txtE.setEnabled(true);
    lblA.setEnabled(true);
    lblB.setEnabled(true);
    lblC.setEnabled(true);
    lblD.setEnabled(true);
    lblE.setEnabled(true);
    
    txtqtd.setEnabled(false);
    lblqtd.setEnabled(false);
    }//GEN-LAST:event_op1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      perguntas[cont] = perguntas[cont] + cont +"-"+txtpergunta.getText() + "\n";
        
         if (op1.isSelected()){
      
               perguntas[cont] = perguntas[cont] + "\nA) " + txtA.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "B) " + txtB.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "C) " + txtC.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "D) " + txtD.getText() + "\n";
               perguntas[cont] = perguntas[cont] + "E) " + txtE.getText() + "\n";
               
             cont++;
                lblnum.setText(cont+".");
                          }else{        
            if (op2.isSelected()){
              int linhas = Integer.parseInt(txtqtd.getValue().toString());
              for(int i=1; i <= linhas ; i++){
                 perguntas[cont]= perguntas[cont]+ "__________________________________________________________";
                 perguntas[cont]= perguntas[cont]+ "_____________________________" + "\n";
              
              }
                cont++;
                 lblnum.setText(cont+".");
                 
         }else{
                      
           JOptionPane.showMessageDialog(null,"Selecione a opção de respostas");           
                      }
         
         }
    
         
         
         txtpergunta.setText("");         
           txtA.setText(""); 
           txtB.setText(""); 
           txtC.setText(""); 
           txtD.setText(""); 
           txtE.setText(""); 
            txtqtd.setValue(1);
            buttonGroup1.setSelected(null, false);
            op1.setSelected(false);
            op2.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
voltar=true;
        panelChamar.setViewportView(new GUI_Gerar1().panel);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       for(int k = 1; k <= cont; k++){
    perguntas[k]= "";
       }
        cont=1;
   lblnum.setText(cont+".");

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_GerarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_GerarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_GerarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_GerarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_GerarPerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblnum;
    private javax.swing.JLabel lblqtd;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    public static final javax.swing.JPanel panel = new javax.swing.JPanel();
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextArea txtpergunta;
    private javax.swing.JSpinner txtqtd;
    // End of variables declaration//GEN-END:variables
}
