/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import static View.GUI_GerarPerguntas.voltar;
import static View.GUI_Index.panelChamar;
import static java.awt.SystemColor.info;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author lab0519
 */
public class GUI_Gerar1 extends javax.swing.JFrame {

    static String aplicador,disciplina,objetivo, semestre, periodo, serie, datadaprova;
   // static Date datadaprova;
    public GUI_Gerar1() {
  /*String laf="";  
  
try {  
  
            try {  
                //TENTA USAR O NIMBUS  
                UIManager.LookAndFeelInfo[] info = UIManager.getInstalledLookAndFeels();  
  
                if (laf.length() == 0) {  
                    laf = "NimbusLookAndFeel";  
                }  
  
                for (UIManager.LookAndFeelInfo lookAndFeelInfo : info) {  
                    if (lookAndFeelInfo.getClassName().contains(laf)) {  
                        UIManager.setLookAndFeel(lookAndFeelInfo.getClassName());  
                        break;  
                    }  
                }  
  
            } catch (Exception ex) {  
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());  
            }  
  
        } catch (ClassNotFoundException ex) {  
        } catch (InstantiationException ex) {  
        } catch (IllegalAccessException ex) {  
        } catch (UnsupportedLookAndFeelException ex) {  
}  */
        initComponents();
        
     
 
        
        




        
        if (voltar == true){
        txtaplicador.setText(aplicador);
      txtobjetivo.setText(objetivo);
    txtdisciplina.setText(disciplina);
    combosemestre.setSelectedItem(semestre);
  comboperiodo.setSelectedItem(periodo);
       txtserie.setText(serie);
       
        DateFormat formate = new SimpleDateFormat("dd/MM/yyyy");
        Date dte=null;
            try {
                dte = (java.util.Date) formate.parse(datadaprova);               
               
            } catch (ParseException ex) {
                Logger.getLogger(GUI_Gerar1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            txtdata.setDate(dte);
            
        panelChamar.setViewportView(new GUI_GerarPerguntas().panel);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtaplicador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdisciplina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combosemestre = new javax.swing.JComboBox();
        comboperiodo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobjetivo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMaximumSize(new java.awt.Dimension(545, 395));
        panel.setMinimumSize(new java.awt.Dimension(545, 395));
        panel.setPreferredSize(new java.awt.Dimension(545, 395));
        panel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Data:");
        panel.add(jLabel1);
        jLabel1.setBounds(390, 80, 40, 20);
        panel.add(txtaplicador);
        txtaplicador.setBounds(140, 80, 220, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Nome do Aplicador:");
        panel.add(jLabel2);
        jLabel2.setBounds(20, 80, 120, 20);
        panel.add(txtdata);
        txtdata.setBounds(440, 80, 90, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Disciplina:");
        panel.add(jLabel3);
        jLabel3.setBounds(20, 110, 120, 20);
        panel.add(txtdisciplina);
        txtdisciplina.setBounds(140, 110, 220, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Período:");
        panel.add(jLabel4);
        jLabel4.setBounds(390, 110, 60, 20);
        panel.add(txtserie);
        txtserie.setBounds(140, 140, 60, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Semestre:");
        panel.add(jLabel5);
        jLabel5.setBounds(230, 140, 70, 20);

        combosemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º", "2º" }));
        panel.add(combosemestre);
        combosemestre.setBounds(300, 140, 60, 20);

        comboperiodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Noturno" }));
        panel.add(comboperiodo);
        comboperiodo.setBounds(440, 110, 90, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Série / Módulo:");
        panel.add(jLabel7);
        jLabel7.setBounds(20, 140, 120, 20);

        txtobjetivo.setColumns(20);
        txtobjetivo.setRows(5);
        jScrollPane1.setViewportView(txtobjetivo);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(140, 170, 390, 100);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CABEÇALHO");
        panel.add(jLabel8);
        jLabel8.setBounds(0, 10, 550, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setText("Objetivo:");
        panel.add(jLabel9);
        jLabel9.setBounds(20, 170, 60, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1416623445_Next.png"))); // NOI18N
        jButton1.setText("Avançar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(290, 320, 90, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1416623432_edit-clear.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(190, 320, 90, 40);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 545, 395);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(txtdisciplina.getText().equals("") || (txtserie.getText().equals("")) || txtaplicador.getText().equals("") || txtobjetivo.getText().equals("")){

    JOptionPane.showMessageDialog(null,"Preencha todos campos!");
}     else{
        aplicador = txtaplicador.getText();
        objetivo = txtobjetivo.getText();
        disciplina = txtdisciplina.getText();
        semestre = combosemestre.getSelectedItem().toString();
        periodo = comboperiodo.getSelectedItem().toString();
        serie = txtserie.getText();
        datadaprova = new SimpleDateFormat("dd/MM/yyyy").format(txtdata.getDate());
        
        
        panelChamar.setViewportView(new GUI_GerarPerguntas().panel);  
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txtaplicador.setText("");
       txtobjetivo.setText("");
       txtserie.setText("");
       txtdata.setDate(null);
    
       txtdisciplina.setText("");
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Gerar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Gerar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Gerar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Gerar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Gerar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboperiodo;
    private javax.swing.JComboBox combosemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JPanel panel = new javax.swing.JPanel();
    private javax.swing.JTextField txtaplicador;
    public static final com.toedter.calendar.JDateChooser txtdata = new com.toedter.calendar.JDateChooser();
    private javax.swing.JTextField txtdisciplina;
    private javax.swing.JTextArea txtobjetivo;
    private javax.swing.JTextField txtserie;
    // End of variables declaration//GEN-END:variables

    private static class LookAndFeelImpl extends LookAndFeel {

        public LookAndFeelImpl() {
        }

        @Override
        public String getName() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

                @Override
                public String getID() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public String getDescription() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public boolean isNativeLookAndFeel() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public boolean isSupportedLookAndFeel() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
    }
}
