/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import static View.GUI_Gerar1.aplicador;
import static View.GUI_Gerar1.datadaprova;
import static View.GUI_Gerar1.disciplina;
import static View.GUI_Gerar1.objetivo;
import static View.GUI_Gerar1.periodo;
import static View.GUI_Gerar1.semestre;
import static View.GUI_Gerar1.serie;
import static View.GUI_Gerar1.txtdata;
import static View.GUI_GerarPerguntas.cont;
import static View.GUI_GerarPerguntas.perguntas;
import static View.GUI_Index.panelChamar;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import gerador.de.prova.Main;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lab0519
 */
public class GUI_Finalizar extends javax.swing.JFrame {


static int contador = cont-(cont-1);
    public GUI_Finalizar() {
        initComponents();
         lblaplicador.setText(aplicador);
        lblobjetivo.setText(objetivo); 
        lbldisciplina.setText(disciplina); 
        lblsemestre.setText(semestre);                
        lblperiodo.setText(periodo);
        lblserie.setText(serie); 
        lbldata.setText(datadaprova); 
        
        lblperguntas.setText(perguntas[contador]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblaplicador = new javax.swing.JLabel();
        lbldisciplina = new javax.swing.JLabel();
        lblsemestre = new javax.swing.JLabel();
        lblserie = new javax.swing.JLabel();
        lblperiodo = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblperguntas = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblobjetivo = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMaximumSize(new java.awt.Dimension(545, 395));
        panel.setMinimumSize(new java.awt.Dimension(545, 395));
        panel.setPreferredSize(new java.awt.Dimension(545, 395));
        panel.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gerar.png"))); // NOI18N
        jButton1.setText("Gerar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(230, 350, 100, 35);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PERGUNTAS");
        panel.add(jLabel10);
        jLabel10.setBounds(0, 200, 550, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Nome do Aplicador:");
        panel.add(jLabel2);
        jLabel2.setBounds(20, 50, 120, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Disciplina:");
        panel.add(jLabel3);
        jLabel3.setBounds(20, 80, 120, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Série / Módulo:");
        panel.add(jLabel7);
        jLabel7.setBounds(20, 110, 120, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setText("Objetivo:");
        panel.add(jLabel9);
        jLabel9.setBounds(20, 140, 60, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Período:");
        panel.add(jLabel4);
        jLabel4.setBounds(390, 80, 60, 20);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Data:");
        panel.add(jLabel1);
        jLabel1.setBounds(390, 50, 40, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Semestre:");
        panel.add(jLabel5);
        jLabel5.setBounds(230, 110, 70, 20);

        lblaplicador.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblaplicador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lblaplicador);
        lblaplicador.setBounds(130, 50, 250, 20);

        lbldisciplina.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbldisciplina.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lbldisciplina);
        lbldisciplina.setBounds(130, 80, 250, 20);

        lblsemestre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblsemestre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lblsemestre);
        lblsemestre.setBounds(300, 110, 110, 20);

        lblserie.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblserie.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lblserie);
        lblserie.setBounds(110, 110, 110, 20);

        lblperiodo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblperiodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lblperiodo);
        lblperiodo.setBounds(440, 80, 80, 20);

        lbldata.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbldata.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(lbldata);
        lbldata.setBounds(440, 50, 80, 20);

        lblperguntas.setEditable(false);
        lblperguntas.setColumns(20);
        lblperguntas.setRows(5);
        jScrollPane1.setViewportView(lblperguntas);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 420, 110);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("FINALIZAR");
        panel.add(jLabel16);
        jLabel16.setBounds(0, 10, 550, 30);

        lblobjetivo.setEditable(false);
        lblobjetivo.setColumns(20);
        lblobjetivo.setRows(5);
        jScrollPane2.setViewportView(lblobjetivo);

        panel.add(jScrollPane2);
        jScrollPane2.setBounds(90, 140, 430, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerda.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(20, 260, 40, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/direita.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel.add(jButton3);
        jButton3.setBounds(500, 260, 40, 30);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 545, 395);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        gerar();
    }catch(IOException ex){
            JOptionPane.showMessageDialog(null,ex);
            }
    panelChamar.setViewportView(new GUI_Inicio().panel);  

    }//GEN-LAST:event_jButton1ActionPerformed
  public static void gerar() throws IOException{
      JFileChooser dlgabrir = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf",".pdf");  
        
dlgabrir.addChoosableFileFilter(filter);  
dlgabrir.setAcceptAllFileFilterUsed(false);  
        dlgabrir.showSaveDialog(null);
        
    String url = dlgabrir.getSelectedFile().getCanonicalPath();
url = url.replace("\\", "/");
   

      
       Document document = new Document();

		try {
                          
        

            
			PdfWriter.getInstance(document, new FileOutputStream(url+".pdf"));
			document.open(); //Abrindo o documento
			//Deve-se adicionar corretamente o endereço da imagem.
			Image image = Image.getInstance(Main.class.getClassLoader().getResource("imagens/cabecalho.png"));
  float x =26,y=103*6;
			image.setAbsolutePosition(x,y);

			
			document.add(image);
                        
Font f2 = new Font (Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL);
float led;
			String disciplin = "                     "+disciplina;
                         Paragraph p1 = new Paragraph(disciplin,f2);
              p1.setSpacingBefore(-18);
                       
                          led = 95;
                         p1.setLeading(led);
                            document.add(p1);
                            
                          String modulo = "                     "+serie;
                         Paragraph p2 = new Paragraph(modulo,f2);
              p2.setSpacingBefore(10);
                       
                         led = 95;
                         p1.setLeading(led);
                            document.add(p2);  
                            
                                 String period = "                                                      "+periodo;
                         Paragraph p3 = new Paragraph(period,f2);
              p3.setSpacingBefore(-96);
                      
                         led = 95;
                         p3.setLeading(led);
                            document.add(p3);  
                            
                                String semestr = "                                                                               ";
                                semestr = semestr + "                                ";
                                        semestr = semestr + semestre;
                         Paragraph p4 = new Paragraph(semestr,f2);
              p4.setSpacingBefore(-96);
                      
                         led = 95;
                         p4.setLeading(led);
                            document.add(p4); 
                            
                            String professo = "                     "+aplicador;
                         Paragraph p5 = new Paragraph(professo,f2);
              p5.setSpacingBefore(-73);
                       
                         led = 95;
                         p5.setLeading(led);
                            document.add(p5); 
                            
                            
                            String data = "                                                                               ";
                            data = data + "                                                            ";
                                                             data = data + "              "+datadaprova;
                         Paragraph p6 = new Paragraph(data,f2);
              p6.setSpacingBefore(-94);
                       
                         led = 95;
                         p6.setLeading(led);
                            document.add(p6); 
                            
                            
                                String objetiv = "                     "+objetivo;
                         Paragraph p7 = new Paragraph(objetiv,f2);
              p7.setSpacingBefore(-80);
                       
                         led = 95;
                         p7.setLeading(led);
                            document.add(p7); 
                            
                                    String pergunt="";
                                      
                                      for (int i=0; i <= cont; i++){
                                          if (!perguntas[i].equals("")){
                                      pergunt = pergunt + perguntas[i] + "\n";
                                          }
                                          }
                                      Paragraph p8 = new Paragraph(pergunt,f2);
             p8.setSpacingBefore(70);
                       
                      /*   led = 95;
                         p8.setLeading(led);*/
                            document.add(p8);     
                            
                            
                          
			document.close();
			
			
			//Mensagem que aparece no console caso tudo dê certo
			System.out.println("Imagem na célula");
                        
              
                        
                    
                
                       
                        
		} catch (DocumentException de) {
			System.err.println(de.getMessage());
		} catch (IOException ioe) {
			System.err.println(ioe.getMessage());
		}
                       
		 Desktop.getDesktop().open(new File(url+".pdf"));

	}
 
 

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  if (contador > cont){
              JOptionPane.showMessageDialog(null,"A prova não possui mais perguntas");
              contador--;
     }else{                 
         lblperguntas.setText(perguntas[contador]);
          contador++;
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
     if (contador == 1){
              JOptionPane.showMessageDialog(null,"A prova não possui mais perguntas");
     }else{         
         contador--;
         lblperguntas.setText(perguntas[contador]);
          }
 
     
        


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Finalizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblaplicador;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lbldisciplina;
    private javax.swing.JTextArea lblobjetivo;
    private javax.swing.JTextArea lblperguntas;
    private javax.swing.JLabel lblperiodo;
    private javax.swing.JLabel lblsemestre;
    private javax.swing.JLabel lblserie;
    public static final javax.swing.JPanel panel = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}
