/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno tarde
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        new Thread() {
            
            public void run(){
                
                for (int i=0; i<101; i++){
                   try{
                    
                       sleep(60); 
                        
                        progress.setValue(i);
                
                        if(progress.getValue() == 10){
                          mostrar.setText("Carregando...");  
                           sleep(1000); 
                          
                           }else if (progress.getValue() <=30){
                            mostrar.setText("Carregando telas da aplicação...");
                          sleep(50);  
                          
                           } else if (progress.getValue() <=99){
                            mostrar.setText("Carregando imagens...");
                            
                             }else{
                            mostrar.setText("Carregamento concluido");
                            
                            sleep(1500);
                        
                        new GUI_Index().setVisible(true);
                           dispose();
                        }
                        
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
            
        }.start();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();
        mostrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        progress.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(progress);
        progress.setBounds(0, 290, 390, 20);
        getContentPane().add(mostrar);
        mostrar.setBounds(190, 270, 190, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abc.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 90, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/10805376_723243647762630_1725328289_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 430, 370);

        setSize(new java.awt.Dimension(385, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mostrar;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
